### ISSUE TITLE
fatal error: sodium.h: No such file or directory

### ISSUE THREAD

**Issue by virtualjj** [krisklosterman/node-open-mining-portal#11]
On Ubuntu Ubuntu 16.04.3 I got the following error:

```
stratumuser@ip-x-x-x-x:~/nomp$ npm update

> multi-hashing@0.0.9 install /home/stratumuser/nomp/node_modules/multi-hashing
> node-gyp rebuild

make: Entering directory '/home/stratumuser/nomp/node_modules/multi-hashing/build'
  CXX(target) Release/obj.target/multihashing/multihashing.o
In file included from ../multihashing.cc:27:0:
../equi.h:18:20: fatal error: sodium.h: No such file or directory
compilation terminated.
multihashing.target.mk:145: recipe for target 'Release/obj.target/multihashing/multihashing.o' failed
make: *** [Release/obj.target/multihashing/multihashing.o] Error 1
make: Leaving directory '/home/stratumuser/nomp/node_modules/multi-hashing/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/stratumuser/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.4.0-1041-aws
gyp ERR! command "/home/stratumuser/.nvm/versions/node/v8.9.4/bin/node" "/home/stratumuser/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/stratumuser/nomp/node_modules/multi-hashing
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! multi-hashing@0.0.9 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the multi-hashing@0.0.9 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

The error is `fatal error: sodium.h: No such file or directory`.

These are the steps I used to install:

```
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | sh
source ~/.profile
nvm install 8.9.4
nvm use 8.9.4
nvm alias default 8.9.4
git clone https://github.com/krisklosterman/node-open-mining-portal nomp
cd nomp
npm update
```

I tried installing package `libsodium18` but got the same error. 

Then I tried installing `libsodium-dev` and `npm update` appears to work now. Here are the last few lines of output:

```
.
.
  SOLINK_MODULE(target) Release/obj.target/multihashing.node
  COPY Release/multihashing.node
make: Leaving directory '/home/stratumuser/nomp/node_modules/multi-hashing/build'
npm notice created a lockfile as package-lock.json. You should commit this file.
+ stratum-pool@0.1.9
added 3 packages in 20.404s
```
Is this expected behaviour? I'm raising this as a potential issue as the package is not required for zone117x/node-open-mining-portal. Thanks in advance!

**Comment by ghost** [comment]
https://github.com/pyca/pynacl/issues/79

Problem with libsodium on Ubuntu. On Debian there is no problem.
Did You install libsodium under root or user?

On Deb I install all under root, pool start under user without sudo. 

Is there same error with my repo?
